twig:
    default_path: '%kernel.project_dir%/templates'
    form_themes: ['bootstrap_4_layout.html.twig']
    globals:
        locales: '%app_locales%'
        image_product_dir: 'uploads/product'
        image_product_subdir_middle: 'uploads/product/800'
        image_product_subdir_small: 'uploads/product/150'
        image_item_dir: 'uploads/product/item'
        image_category_dir: 'uploads/category'
        image_article_dir: 'uploads/article'
        image_order_dir: 'uploads/order'
